kind: MLApp
metadata:
  name: pytorch
spec:
  package_manager: "pip{{.python_version.value}}"
  packages:
  - names:
    {{- range $i, $value := .packages }}
    - "{{ $value }}"
    {{- end }}
    manager: "pip{{.python_version.value}}"
  default_mount_path: "/notebooks"
  tasks:
  - name: standalone
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: "kuberlab/fastai:latest-gpu"
        cpu: "kuberlab/fastai:latest-cpu"
      command: >-
        python spatial_transformer.py --batch-size 64 --epochs 10
        --data-dir $DATA_DIR --training_dir $TRAINING_DIR
      workdir: "$SRC_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 4Gi
      default_volume_mapping: true
  - name: mnist-example
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: "kuberlab/fastai:latest-gpu"
        cpu: "kuberlab/fastai:latest-cpu"
      command: >-
        python mnist.py --data-dir $DATA_DIR --training_dir $TRAINING_DIR --out-dir $TRAINING_DIR
        --batch-size 64 --epochs 3
      workdir: "$EXAMPLES_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 3000m
          memory: 4Gi
      default_volume_mapping: true
  - name: convert-to-tf
    resources:
    - name: worker
      replicas: 1
      restartPolicy: Never
      maxRestartCount: 0
      allowFail: true
      images:
        gpu: "kuberlab/fastai:latest-gpu"
        cpu: "kuberlab/fastai:latest-cpu"
      command: >-
        torch2tf --input $TRAINING_DIR/checkpoint.pth.tar
        --model-class mnist:Net --input-shape 1,1,28,28 --output $TRAINING_DIR/tf_model
        # && python upload_model.py --model-name mnist-pytorch-tf --version 1.0.0 --from-path $TRAINING_DIR/tf_model
      workdir: "$EXAMPLES_DIR"
      resources:
        accelerators:
          gpu: 0
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 1000m
          memory: 4Gi
      default_volume_mapping: true
  uix:
  - name: jupyter
    displayName: Jupyter
    images:
      gpu: "kuberlab/fastai:latest-gpu"
      cpu: "kuberlab/fastai:latest-cpu"
    resources:
      accelerators:
        gpu: 0
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 1000m
        memory: 4Gi
    ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
    default_volume_mapping: true
  volumes:
  - isLibDir: false
    name: training
    clusterStorage: {{ .storage.value }}
  - gitRepo:
      repository: {{ gitRepo .src.value }}
    isLibDir: false
    name: src
    subPath: {{ gitSubPath .src.value }}
  - gitRepo:
      repository: {{ gitRepo "https://github.com/kuberlab/pytorch-examples" }}
    isLibDir: false
    name: examples
    subPath: {{ gitSubPath "https://github.com/kuberlab/pytorch-examples" }}
  - isLibDir: true
    name: lib
    clusterStorage: {{ .storage.value }}
  - isLibDir: false
    name: data
    {{- if .dataset.value }}
    datasetFS:
      workspace: {{ .dataset.workspace }}
      dataset: {{ .dataset.value }}
      version: {{ .dataset.version }}
    {{- else }}
    clusterStorage: {{ .storage.value }}
    {{- end }}
  - isLibDir: false
    mountPath: /notebooks
    name: code
    subPath: code
    clusterStorage: {{ .storage.value }}
